CREATE TABLE Node (
	nid INTEGER PRIMARY KEY AUTOINCREMENT
	, label VARCHAR(50) NOT NULL
);

CREATE TABLE Edge (
	eid INTEGER PRIMARY KEY AUTOINCREMENT
	, label VARCHAR(50) NOT NULL
	, out_nid INTEGER NOT NULL
	, in_nid INTEGER NOT NULL
	, FOREIGN KEY(out_nid) REFERENCES Node(nid) 
	, FOREIGN KEY(in_nid) REFERENCES Node(nid)
);